# Generated by Django 4.2.2 on 2023-06-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('birthday', models.CharField(blank=True, max_length=20, null=True)),
                ('featured_img', models.ImageField(null=True, upload_to='images/')),
                ('classified', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
